name: GitHub/SonarCloud Integration
description: A GitHub action to automate SonarCloud API interactions
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "monitor"
  color: "purple"
inputs:
  sonarUrl:
    description: "The SonarCloud URL"
    default: "https://sonarcloud.io"
  sonarToken:
    description: "The SonarCloud bearer token"
    required: true
