import { parseApiResponse, type RawApiResponse } from "./api-response";

describe("api-response", () => {
  it("should return the transformed response", () => {
    const rawApiResponse: RawApiResponse = {
      total: 2,
      p: 1,
      ps: 100,
      paging: { pageIndex: 1, pageSize: 100, total: 2 },
      effortTotal: 2,
      debtTotal: 2,
      issues: [
        {
          key: "AY73m1ukccyUyDcrAut7",
          rule: "typescript:S3863",
          severity: "MINOR",
          component:
            "orgname_github-action-sonarcloud:src/main/decorate-files.ts",
          project: "orgname_github-action-sonarcloud",
          line: 2,
          hash: "1b139f5da70e40d24070acfa8c139677",
          textRange: {
            startLine: 2,
            endLine: 2,
            startOffset: 33,
            endOffset: 51,
          },
          flows: [],
          status: "OPEN",
          message: "'@/github/comment' imported multiple times.",
          effort: "1min",
          debt: "1min",
          assignee: "username@provider",
          author: "author@email.tld",
          tags: ["es2015"],
          creationDate: "2024-04-19T20:16:16+0200",
          updateDate: "2024-04-19T20:24:56+0200",
          type: "CODE_SMELL",
          organization: "orgname",
          pullRequest: "34",
          cleanCodeAttribute: "CONVENTIONAL",
          cleanCodeAttributeCategory: "CONSISTENT",
          impacts: [{ softwareQuality: "MAINTAINABILITY", severity: "LOW" }],
        },
        {
          key: "AY73m1ukccyUyDcrAut8",
          rule: "typescript:S3863",
          severity: "MINOR",
          component:
            "orgname_github-action-sonarcloud:src/main/decorate-files.ts",
          project: "orgname_github-action-sonarcloud",
          line: 3,
          hash: "b846a38eb2c828b7f3d92e8c012e4b0f",
          textRange: {
            startLine: 3,
            endLine: 3,
            startOffset: 36,
            endOffset: 54,
          },
          flows: [],
          status: "OPEN",
          message: "'@/github/comment' imported multiple times.",
          effort: "1min",
          debt: "1min",
          assignee: "username@provider",
          author: "author@email.tld",
          tags: ["es2015"],
          creationDate: "2024-04-19T20:16:16+0200",
          updateDate: "2024-04-19T20:24:56+0200",
          type: "CODE_SMELL",
          organization: "orgname",
          pullRequest: "34",
          cleanCodeAttribute: "CONVENTIONAL",
          cleanCodeAttributeCategory: "CONSISTENT",
          impacts: [{ softwareQuality: "MAINTAINABILITY", severity: "LOW" }],
        },
      ],
      components: [
        {
          organization: "orgname",
          key: "orgname_github-action-sonarcloud:src/main/decorate-files.ts",
          uuid: "AY73m1kQccyUyDcrAuta",
          enabled: true,
          qualifier: "FIL",
          name: "decorate-files.ts",
          longName: "src/main/decorate-files.ts",
          path: "src/main/decorate-files.ts",
          pullRequest: "34",
        },
        {
          organization: "orgname",
          key: "orgname_github-action-sonarcloud",
          uuid: "AY73m1hD3ivnCy_Ozovt",
          enabled: true,
          qualifier: "TRK",
          name: "GitHub Action SonarCloud",
          longName: "GitHub Action SonarCloud",
          pullRequest: "34",
        },
      ],
      organizations: [{ key: "orgname", name: "Steven Jimenez" }],
      facets: [],
    };
    const result = parseApiResponse(rawApiResponse);

    expect(result).toEqual({
      total: 2,
      p: 1,
      ps: 100,
      paging: { pageIndex: 1, pageSize: 100, total: 2 },
      effortTotal: 2,
      debtTotal: 2,
      issues: [
        {
          key: "AY73m1ukccyUyDcrAut7",
          rule: "typescript:S3863",
          severity: "MINOR",
          component:
            "orgname_github-action-sonarcloud:src/main/decorate-files.ts",
          file: "src/main/decorate-files.ts",
          project: "orgname_github-action-sonarcloud",
          line: 2,
          hash: "1b139f5da70e40d24070acfa8c139677",
          textRange: {
            startLine: 2,
            endLine: 2,
            startOffset: 33,
            endOffset: 51,
          },
          flows: [],
          status: "OPEN",
          message: "'@/github/comment' imported multiple times.",
          effort: "1min",
          debt: "1min",
          assignee: "username@provider",
          author: "author@email.tld",
          tags: ["es2015"],
          creationDate: new Date("2024-04-19T20:16:16+0200"),
          updateDate: new Date("2024-04-19T20:24:56+0200"),
          type: "CODE_SMELL",
          organization: "orgname",
          pullRequest: "34",
          cleanCodeAttribute: "CONVENTIONAL",
          cleanCodeAttributeCategory: "CONSISTENT",
          impacts: [{ softwareQuality: "MAINTAINABILITY", severity: "LOW" }],
        },
        {
          key: "AY73m1ukccyUyDcrAut8",
          rule: "typescript:S3863",
          severity: "MINOR",
          component:
            "orgname_github-action-sonarcloud:src/main/decorate-files.ts",
          file: "src/main/decorate-files.ts",
          project: "orgname_github-action-sonarcloud",
          line: 3,
          hash: "b846a38eb2c828b7f3d92e8c012e4b0f",
          textRange: {
            startLine: 3,
            endLine: 3,
            startOffset: 36,
            endOffset: 54,
          },
          flows: [],
          status: "OPEN",
          message: "'@/github/comment' imported multiple times.",
          effort: "1min",
          debt: "1min",
          assignee: "username@provider",
          author: "author@email.tld",
          tags: ["es2015"],
          creationDate: new Date("2024-04-19T20:16:16+0200"),
          updateDate: new Date("2024-04-19T20:24:56+0200"),
          type: "CODE_SMELL",
          organization: "orgname",
          pullRequest: "34",
          cleanCodeAttribute: "CONVENTIONAL",
          cleanCodeAttributeCategory: "CONSISTENT",
          impacts: [{ softwareQuality: "MAINTAINABILITY", severity: "LOW" }],
        },
      ],
      components: [
        {
          organization: "orgname",
          key: "orgname_github-action-sonarcloud:src/main/decorate-files.ts",
          uuid: "AY73m1kQccyUyDcrAuta",
          enabled: true,
          qualifier: "FIL",
          name: "decorate-files.ts",
          longName: "src/main/decorate-files.ts",
          path: "src/main/decorate-files.ts",
          pullRequest: "34",
        },
        {
          organization: "orgname",
          key: "orgname_github-action-sonarcloud",
          uuid: "AY73m1hD3ivnCy_Ozovt",
          enabled: true,
          qualifier: "TRK",
          name: "GitHub Action SonarCloud",
          longName: "GitHub Action SonarCloud",
          pullRequest: "34",
        },
      ],
      organizations: [{ key: "orgname", name: "Steven Jimenez" }],
      facets: [],
      rules: [],
      users: [],
    });
  });
});
