export enum Facet {
  Projects = "projects",
  ModuleUuids = "moduleUuids",
  FileUuids = "fileUuids",
  AssignedToMe = "assigned_to_me",
  Severities = "severities",
  Statuses = "statuses",
  IssueStatuses = "issueStatuses",
  Resolutions = "resolutions",
  Rules = "rules",
  Assignees = "assignees",
  Author = "author",
  Directories = "directories",
  Languages = "languages",
  Tags = "tags",
  Types = "types",
  OwaspTop10 = "owaspTop10",
  SansTop25 = "sansTop25",
  CWE = "cwe",
  CreatedAt = "createdAt",
  SonarSourceSecurity = "sonarsourceSecurity",
  ImpactSoftwareQualities = "impactSoftwareQualities",
  ImpactSeverity = "impactSeverity",
  CleanCodeAttributeCategories = "cleanCodeAttributeCategories",
}
