export enum SonarSourceSecurity {
  BufferOverflow = "buffer-overflow",
  Permission = "permission",
  SqlInjection = "sql-injection",
  CommandInjection = "command-injection",
  PathTraversalInjection = "path-traversal-injection",
  LdapInjection = "ldap-injection",
  XPathInjection = "xpath-injection",
  RCE = "rce",
  DOS = "dos",
  SSRF = "ssrf",
  CSRF = "csrf",
  XSS = "xss",
  LogInjection = "log-injection",
  HttpResponseSplitting = "http-response-splitting",
  OpenRedirect = "open-redirect",
  XXE = "xxe",
  ObjectInjection = "object-injection",
  WeakCryptography = "weak-cryptography",
  Auth = "auth",
  InsecureConf = "insecure-conf",
  EncryptData = "encrypt-data",
  Traceability = "traceability",
  FileManipulation = "file-manipulation",
  Others = "others",
}
